### PR TITLE
Fix broken cop in ruby.yml

### PR DESCRIPTION
**Pull request by penous**
- update readme to reference this ruby.yml.
- update cop to match latest rubocop version.

### CODE REVIEW

**Comment by penous** [comment]
@Reprazent, @pjaspers Is this ok?

Met dank aan @lewis-fidlers.

**Comment by Reprazent** [comment]
Did you adjust the `~/.rubocop.yml` on marleen?

**Comment by Reprazent** [comment]
Turns out: github still redirects `styleguides` to `standards`, which is nice!

**Comment by lewis-fidlers** [comment]
Marleen hasn't been updated yet. Change hasn't been tested with older rubocop versions yet either so perhaps this won't work. :)

**Comment by Reprazent** [comment]
On the other hand: Failing builds will force people to upgrade. 
So I'd say go update marleen, and we'll see what builds die ;-)

**Pull request merged**
