### PR TITLE
Add info on how to override a styleguide

### PR DESCRIPTION
**Pull request by Reprazent**
Some info on how to override styleguides per project

### CODE REVIEW

**Comment by To1ne** [comment]
Does the override file need to contain all the rules, or does it fall back to `~/.rubocop.yml`?

**Comment by Reprazent** [comment]
@To1ne good point: You can make it inherit from the one at `https://raw.githubusercontent.com/10to1/styleguides/master/guides/ruby.yml`. I will already make the `~/.rubocop.yml` one inherit from there that way it will always be up to date.

**Comment by Reprazent** [comment]
I got that from [here](https://github.com/bbatsov/rubocop#configuration)

**Comment by To1ne** [comment]
Inherit from a file on the internetz?
Wouldn't it be better to just `inherit_from: ~/.rubocop.yml`?

**Comment by Reprazent** [comment]
Which would be the same on CI, but would keep working on your machine when you don't have sed internetz

**Comment by To1ne** [comment]
Thanks! I'll stop nagging now.
hug

**Pull request merged**
