### PR TITLE
Some adustments to collection methods

### PR DESCRIPTION
**Pull request by Reprazent**
- Avoid the conflicts with `Style/CollectionMethods` and
  `Style/EachWithObject`

- Use both map & collect:
  map: For calling methods on/manipulating each object of a collection
  collect: For collecting the return values of the iteration

### CODE REVIEW

**Comment by Reprazent** [comment]
This includes #11

**Comment by To1ne** [comment]
😍  for 7afac289712d2c5841fa59304d4fc6a05c200a21's commit message.

**Comment by Reprazent** [comment]
It has a typo :-( I wanted to collect `stinks?` not `stinks!`

**Comment by To1ne** [comment]
That `stinks!`.

**Pull request merged**
